export const FETCHING_START = 'FETCHING_START'
export const FETCHING_SUCCESS = 'FETCHING_SUCCESS'
export const FETCHING_FAIL = 'FETCHING_FAIL'

export const PRODUCTS_SET = 'PRODUCTS_SET'
export const ORDERS_SET ='ORDERS_SET'
export const CUSTMERS_SET = 'CUSTMERS_SET'

export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_FROM_CART = 'DELETE_FROM_CART'
export const INCREASE_CART_QUANTITY = 'INCREASE_CART_QUANTITY'
export const DECREASE_CART_QUANTITY = 'DECREASE_CART_QUANTITY'
